// Generated by https://quicktype.io

export interface ITask {
    title?:    string;
    id:       string;
    user:     User;
    comments?: Comment[];
}

export interface Comment {
    text: string;
    user: User;
}

export interface User {
    name:   string;
    avatar: string;
}
